## Notebook Content

In this notebook, we will clean the data collected from  [__Sprouts__](https://shop.sprouts.com/shop).

## Import Libraries

In [46]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sqlite3 as sql

### Read Data

In [47]:
df = pd.read_csv('Sprouts_All_df.csv')

### Explore Data

In [48]:
df.head()

,Unnamed: 0,URL,CALORY,TOTAL_FAT,SATURATED_FAT,TRANS_FAT,POLYUNSATURATED_FAT,MONOUNSATURATED_FAT,CHOLESTEROL,SODIUM,...,MAGNESIUM,ZINC,SELENIUM,COPPER,MANGANESE,CHROMIUM,FOLIC_ACID,SOLUBLE_FIBER,VITAMIN_B12,PANTOTHENIC_ACID
0,0,https://shop.sprouts.com/shop/categories/133?p...,140,8.0,0.5,0.0,1.5,5.0,0.0,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,https://shop.sprouts.com/shop/categories/133?p...,150,9.0,1.5,0.0,1.0,6.0,0.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,https://shop.sprouts.com/shop/categories/133?p...,130,7.0,0.5,0.0,1.5,5.0,0.0,65.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,https://shop.sprouts.com/shop/categories/133?p...,140,7.0,0.5,0.0,1.5,6.0,0.0,120.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,https://shop.sprouts.com/shop/categories/133?p...,140,8.0,1.0,0.0,1.0,6.0,0.0,200.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df.shape

(1305, 43)

In [50]:
# check about nulls 
df.isnull().sum().sort_values(ascending = False)

FOLIC_ACID               1298
BIOTIN                   1298
CHROMIUM                 1297
SOLUBLE_FIBER            1290
SELENIUM                 1290
IODINE                   1287
VITAMIN_K                1286
PANTOTHENIC_ACID         1280
MANGANESE                1268
ZINC                     1265
FOLATE                   1263
VITAMIN_B12              1256
INSOLUBLE_FIBER          1246
COPPER                   1245
VITAMIN_B6               1237
THIAMIN                  1234
RIBOFLAVIN               1230
NIACIN                   1227
VITAMIN_E                1203
PHOSPHORUS               1195
MAGNESIUM                1177
POLYUNSATURATED_FAT      1058
MONOUNSATURATED_FAT      1052
VITAMIN_A                 686
VITAMIN_C                 677
CALORIES_FROM_FAT         644
INCLUDES_ADDED_SUGARS     540
VITAMIN_D                 452
POTASSIUM                 389
CALCIUM                   107
IRON                      102
TRANS_FAT                 102
CHOLESTEROL                99
DIETARY_FIBER              92
SATURATED_FAT              91
TOTAL_SUGARS               73
PROTEIN                     6
SODIUM                      2
TOTAL_CARBOHYDRATE          1
CALORY                      0
URL                         0
TOTAL_FAT                   0
Unnamed: 0                  0
dtype: int64

As we see, there is a lot of null values, so we must dealling with them

### Drop Columns

Due to the large numbers of null values in some columns, we will drop the columns with more than 400 null values

In [51]:
# Any column with > 400 null will be dropped
col_list_toDrop = ['VITAMIN_C', 'VITAMIN_A','VITAMIN_E','VITAMIN_B6','VITAMIN_B12','VITAMIN_K',
                   'CALORIES_FROM_FAT','FOLIC_ACID','BIOTIN','CHROMIUM','SELENIUM',
                   'IODINE','PANTOTHENIC_ACID','MANGANESE','ZINC','FOLATE','COPPER','THIAMIN',
                   'RIBOFLAVIN','NIACIN','PHOSPHORUS','MAGNESIUM','POLYUNSATURATED_FAT','MONOUNSATURATED_FAT']

In [52]:
df.drop(col_list_toDrop, axis='columns', inplace=True)

In [53]:
#drop unnammed column
df = df.loc[:,~df.columns.str.match("Unnamed:")]

In [54]:
df.columns

Index(['URL', 'CALORY', 'TOTAL_FAT', 'SATURATED_FAT', 'TRANS_FAT',
       'CHOLESTEROL', 'SODIUM', 'TOTAL_CARBOHYDRATE', 'DIETARY_FIBER',
       'TOTAL_SUGARS', 'INCLUDES_ADDED_SUGARS', 'PROTEIN', 'VITAMIN_D',
       'CALCIUM', 'IRON', 'POTASSIUM', 'INSOLUBLE_FIBER', 'SOLUBLE_FIBER'],
      dtype='object')

### Fill Nulls

In [55]:
#fill nulls with 0 
df.fillna(0,inplace = True)

### Add Nedded Columns

As we see above, there is __SUGARS__ , and __INCLUDES_ADDED_SUGARS__ columns which are all about the sugar. As a result, we can combine them into 1 column. Also, __FIBER__, __INSOLUBLE_FIBER__, __SOLUBLE_FIBER__ and __DIETARY_FIBER__ columns meaning the same, so we will combine them into a single column.

In [56]:
df['SUGARS'] = df['TOTAL_SUGARS'] + df['INCLUDES_ADDED_SUGARS']

In [57]:
df['FIBER'] = df['INSOLUBLE_FIBER'] + df['SOLUBLE_FIBER']+ df['DIETARY_FIBER']

In [58]:
#drop the combined columns 
df.drop(['TOTAL_SUGARS','INCLUDES_ADDED_SUGARS', 'INSOLUBLE_FIBER', 'SOLUBLE_FIBER', 'DIETARY_FIBER'], axis=1, inplace=True)

In [59]:
df.columns

Index(['URL', 'CALORY', 'TOTAL_FAT', 'SATURATED_FAT', 'TRANS_FAT',
       'CHOLESTEROL', 'SODIUM', 'TOTAL_CARBOHYDRATE', 'PROTEIN', 'VITAMIN_D',
       'CALCIUM', 'IRON', 'POTASSIUM', 'SUGARS', 'FIBER'],
      dtype='object')

### General check

In [60]:
df.head()

,URL,CALORY,TOTAL_FAT,SATURATED_FAT,TRANS_FAT,CHOLESTEROL,SODIUM,TOTAL_CARBOHYDRATE,PROTEIN,VITAMIN_D,CALCIUM,IRON,POTASSIUM,SUGARS,FIBER
0,https://shop.sprouts.com/shop/categories/133?p...,140,8.0,0.5,0.0,0.0,110.0,16.0,2.0,0.0,22.0,0.0,65.0,0.0,1.0
1,https://shop.sprouts.com/shop/categories/133?p...,150,9.0,1.5,0.0,0.0,120.0,16.0,2.0,0.0,6.0,0.0,450.0,0.0,1.0
2,https://shop.sprouts.com/shop/categories/133?p...,130,7.0,0.5,0.0,0.0,65.0,17.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0
3,https://shop.sprouts.com/shop/categories/133?p...,140,7.0,0.5,0.0,0.0,120.0,16.0,2.0,0.0,23.0,0.0,65.0,0.0,1.0
4,https://shop.sprouts.com/shop/categories/133?p...,140,8.0,1.0,0.0,0.0,200.0,17.0,2.0,0.0,5.0,0.4,380.0,1.0,1.0

In [61]:
df.tail()

,URL,CALORY,TOTAL_FAT,SATURATED_FAT,TRANS_FAT,CHOLESTEROL,SODIUM,TOTAL_CARBOHYDRATE,PROTEIN,VITAMIN_D,CALCIUM,IRON,POTASSIUM,SUGARS,FIBER
1300,https://shop.sprouts.com/shop/categories/153?p...,140,1.5,0.0,0.0,0.0,230.0,30.0,2.0,0.0,10.0,0.4,290.0,4.0,3.0
1301,https://shop.sprouts.com/shop/categories/153?p...,15,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0
1302,https://shop.sprouts.com/shop/categories/153?p...,15,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0
1303,https://shop.sprouts.com/shop/categories/153?p...,30,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0
1304,https://shop.sprouts.com/shop/categories/153?p...,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [62]:
df.sample(5)

,URL,CALORY,TOTAL_FAT,SATURATED_FAT,TRANS_FAT,CHOLESTEROL,SODIUM,TOTAL_CARBOHYDRATE,PROTEIN,VITAMIN_D,CALCIUM,IRON,POTASSIUM,SUGARS,FIBER
337,https://shop.sprouts.com/shop/categories/133?p...,20,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
357,https://shop.sprouts.com/shop/categories/133?p...,250,17.0,2.5,0.0,0.0,105.0,18.0,11.0,0.0,0.0,0.0,0.0,11.0,0.0
1259,https://shop.sprouts.com/shop/categories/153?p...,210,17.0,3.0,0.0,95.0,210.0,10.0,7.0,0.5,60.0,2.0,241.0,3.0,5.0
623,https://shop.sprouts.com/shop/categories/133?p...,130,6.0,0.0,0.0,0.0,85.0,19.0,1.0,0.0,28.0,1.0,319.0,4.0,3.0
1036,https://shop.sprouts.com/shop/categories/153?p...,50,0.5,0.0,0.0,0.0,5.0,10.0,1.0,0.0,0.0,0.0,0.0,5.0,3.0

### Add Data to DataBase

In [65]:
conn = sql.connect('Cleaned_Sprouts_df.db')

In [66]:
df.to_sql('Cleaned_Sprouts_df', conn)